### ISSUE TITLE
net_mig argument name

### ISSUE THREAD

**Issue by guyabel** [jessieyeung/rcbayes#7]
Hi. I really love this package. I spent a good few months of my postdoc going crazy trying to work with old FORTRAN and Matlab code, and then writing my own code using of `optim()` and WinBUGS to fit migration age schedules... all of which were crap. It is great to have a package on CRAN that actually does a solid job of fitting migration age schedules. I included the `mig_calculate_rc()` and `mig_estimate_rc()` from *DemoTools* in a  KOSTAT-UNFPA summer seminar series course I recently ran on migration estimation. 

I was wondering why in the *rcbayes* version there is a `net_mig` argument? Rogers has a section in his net migration requiem [paper](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1538-4632.1990.tb00212.x) on how messy net migration age schedules can be; to quote him:

>Because net rates confound flows with changes in stocks, they hide regularities that seem to prevail among gross flows. Although the latter tend always to follow the conventional age profile, the former exhibit a surprisingly wide variety of shapes

He has some nice plots showing his point with US internal migration data. I have seen some old papers on net migration age schedules, for example [Schroeder & Pittenger](https://read.dukeupress.edu/demography/article/20/2/235/171635/Improving-the-accuracy-of-migration-age-detail-in), but they do not reference Rogers and Castro (it was around the same time) and some of their typologies are very different from a Rogers and Castro age schedule. 

With the above in mind, perhaps you might consider changing the `net_mig` argument name to `mig` (or something else without referencing net)?

**Comment by MJAlexander** [comment]
Hi Guy, thanks so much for your feedback; we are thrilled that you find it useful. We completely agree that it should be renamed to be `mig`, not sure how that improper naming slipped through. @jessieyeung will update on git version and then it should be updated on CRAN in a couple of months.

**Comment by guyabel** [comment]
Super. Many thanks. 

A related follow-up question (if I may). Are there any plans to introduce a `mx` argument for a age-specific migration rate, as in the *DemoTools* version? When I experimented with age-specific migration rates and set `pop` to a vector of 1's with the same length of `net_age` i get a *rstan* error...

```{r} 
library(rcbayes)

ages <- 0:80
net_mig <- c(202,215,167,188,206,189,164,
             158,197,185,176,173,167,198,
             203,237,249,274,319,345,487,
             491,521,505,529,527,521,529,
             507,484,467,439,399,399,380,
             368,310,324,289,292,270,269,
             285,254,245,265,257,258,263,
             253,346,293,332,346,349,355,
             386,346,344,352,331,320,307,
             320,310,258,254,243,256,263,
             183,169,172,160,166,113,132,
             111,130,110,113)
net_mig <- net_mig/sum(net_mig)

mig_estimate_rc(ages = ages, net_mig = net_mig, pop = rep(1, length(ages)),
                pre_working_age = TRUE,
                working_age = TRUE,
                retirement = TRUE,
                post_retirement = FALSE)

# Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
#   Exception: int variable contained non-int values; processing stage=data initialization; variable name=y; base type=int  (in # 'model_rcmodel' at line 8)
# 
# failed to create the sampler; sampling not done
# Stan model 'rcmodel' does not contain samples.
# Error in these_pars[[names(list_of_draws)[i]]] <- list_of_draws[[names(list_of_draws)[i]]][j] : 
#   attempt to select less than one element in OneIndex
```
... or perhaps i am doing something wrong?

**Comment by MJAlexander** [comment]
Hi Guy, thanks. When we were writing this and trying to improve convergence, we found that a Poisson likelihood based model did a bit better than the original Normal specification (and is a bit more 'correct' in terms of inputting the mig and pop counts, rather than assuming a Normal approximation for the rates). With the Poisson spec you can't input rates, just integer counts. That said, convergence was improved once we could specify initial conditions and now there's not much difference between the two likelihoods. It make sense that the user (ie, you!) should be able to specify data either in terms of rates or counts, so we'll work on allowing either type of input.

**Comment by guyabel** [comment]
Great! Many thanks.
